# Generated by Django 2.2.2 on 2019-06-22 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('class_name', models.CharField(max_length=64)),
                ('gpa', models.CharField(blank=True, max_length=64, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('major', models.CharField(max_length=256, null=True)),
                ('uni', models.CharField(max_length=64, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('req', models.CharField(max_length=256, null=True)),
                ('output', models.CharField(max_length=256, null=True)),
                ('tool', models.CharField(max_length=256, null=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='selection.Teacher')),
                ('taker', models.ManyToManyField(blank=True, related_name='author', to='selection.Student')),
            ],
        ),
    ]
