# Generated by Django 2.2.2 on 2019-06-25 15:05

from django.db import migrations, models
import thesis.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20190624_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, storage=thesis.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
